<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <DisableAspireWorkloadDeprecationWarning>true</DisableAspireWorkloadDeprecationWarning>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <ProjectReference Include="..\Momentum.Service\Momentum.Service.csproj" />
    <ProjectReference Include="..\Momentum.Mcp\Momentum.Mcp.csproj" />
  </ItemGroup>

</Project>
