import type { SolutionUseResponse, VoteSummaryResponse } from "@momentum/contracts";
import type { Assert, FieldsExistOn, FieldsExistOnExcept } from "./common.js";
import type { AdoptionStatus, HubItemType, ParticipationStatus } from "./enums.js";

/** Points an engagement record at either side of the hub. */
export interface HubItemRef {
  itemType: HubItemType;
  itemId: string;
}

/** Canonical string form, matching `HubItemReference.TargetKey` on the backend. */
export function targetKey(ref: HubItemRef): string {
  return `${ref.itemType === "Idea" ? "request" : "solution"}:${ref.itemId}`;
}

// ---------------------------------------------------------------------------
// Votes
// ---------------------------------------------------------------------------

/**
 * Upvote state for one item, for the calling user.
 *
 * `votedByMe` is why this is a summary rather than a count: a toggle cannot be
 * rendered without per-user state, and the API was changed to return it for exactly
 * that reason.
 */
export interface VoteSummary {
  itemType: HubItemType;
  itemId: string;
  count: number;
  votedByMe: boolean;
}

export type VoteSummaryMatchesWire = Assert<FieldsExistOn<VoteSummary, VoteSummaryResponse>>;

// ---------------------------------------------------------------------------
// Adoption
// ---------------------------------------------------------------------------

/**
 * A team or project putting a solution to use.
 *
 * `completedAt` is null for every adoption that has not settled — which is the
 * field TypeGen types as a bare `string`. `Adoption.isActive` derives from status
 * rather than from the timestamp so callers do not have to know that.
 */
export interface Adoption {
  id: string;
  solutionId: string;
  startedBy: string;
  /**
   * The adopter's display name, when the backing store can resolve it.
   *
   * `startedBy` is whatever the store keys on, and for Dataverse that is a
   * systemuser GUID — which renders as "Someone" everywhere a name is expected.
   * Optional, exactly like `ActivityEntry.actorName`: hosts whose key is already an
   * identity (the .NET side stores a UserId) omit it and callers fall back.
   */
  startedByName?: string | null;
  projectName: string;
  team: string | null;
  status: AdoptionStatus;
  startedAt: string;
  updatedAt: string;
  completedAt: string | null;
}

// startedByName is resolved by the adapter and has no wire counterpart; every other
// field still has to exist on the generated DTO.
export type AdoptionMatchesWire = Assert<
  FieldsExistOnExcept<Adoption, SolutionUseResponse, "startedByName">
>;

export interface StartAdoptionInput {
  projectName: string;
  team?: string;
  status?: AdoptionStatus;
}

export interface UpdateAdoptionInput {
  status?: AdoptionStatus;
  projectName?: string;
  team?: string;
}

// ---------------------------------------------------------------------------
// Participation
// ---------------------------------------------------------------------------

/**
 * Someone asking to help with an idea or solution.
 *
 * NOTE: `ParticipationResponse` and `RequestParticipationRequest` exist in
 * Momentum.Contracts and are generated by TypeGen, but the generated barrel
 * (`packages/contracts/src/generated.ts`) does not re-export them, so there is no
 * wire type to guard against here yet. Add the assertion once the barrel is
 * regenerated.
 */
export interface Participation {
  id: string;
  itemType: HubItemType;
  itemId: string;
  requestedBy: string;
  message: string;
  status: ParticipationStatus;
  decidedBy: string | null;
  rationale: string | null;
  createdAt: string;
  updatedAt: string;
  decidedAt: string | null;
}

export interface RequestParticipationInput {
  itemType: HubItemType;
  itemId: string;
  message: string;
}

// ---------------------------------------------------------------------------
// Links
// ---------------------------------------------------------------------------

/**
 * A claim that a solution answers an idea.
 *
 * Deliberately attribute-free. An earlier model gave a link a relationship taxonomy
 * (Proposed / Relevant / Existing) and its own approval state, both of which existed
 * only because anyone could propose one. Linking is now a reviewer action, so there
 * is no pending state and nothing left to classify — which means the link is a plain
 * Azure DevOps `Related` link rather than a row in a side table, and it shows up in
 * the work item link panel and in WIQL for free.
 */
export interface IdeaSolutionLink {
  ideaId: string;
  solutionId: string;
  addedBy: string;
  addedAt: string;
}
