import type { SolutionUseResponse, VoteSummaryResponse } from "@momentum/contracts";
import type { Assert, FieldsExistOn, FieldsExistOnExcept } from "./common.js";
import type {
  AdoptionStatus,
  ApprovalState,
  HubItemType,
  ParticipationStatus,
} from "./enums.js";

/** Points an engagement record at either side of the hub. */
export interface HubItemRef {
  itemType: HubItemType;
  itemId: string;
}

/** Canonical string form, matching `HubItemReference.TargetKey` on the backend. */
export function targetKey(ref: HubItemRef): string {
  return `${ref.itemType === "Idea" ? "request" : "solution"}:${ref.itemId}`;
}

// ---------------------------------------------------------------------------
// Votes
// ---------------------------------------------------------------------------

/**
 * Upvote state for one item, for the calling user.
 *
 * `votedByMe` is why this is a summary rather than a count: a toggle cannot be
 * rendered without per-user state, and the API was changed to return it for exactly
 * that reason.
 */
export interface VoteSummary {
  itemType: HubItemType;
  itemId: string;
  count: number;
  votedByMe: boolean;
}

export type VoteSummaryMatchesWire = Assert<FieldsExistOn<VoteSummary, VoteSummaryResponse>>;

// ---------------------------------------------------------------------------
// Adoption
// ---------------------------------------------------------------------------

/**
 * A team or project putting a solution to use.
 *
 * `completedAt` is null for every adoption that has not settled — which is the
 * field TypeGen types as a bare `string`. `Adoption.isActive` derives from status
 * rather than from the timestamp so callers do not have to know that.
 */
export interface Adoption {
  id: string;
  solutionId: string;
  startedBy: string;
  /**
   * The adopter's display name, when the backing store can resolve it.
   *
   * `startedBy` is whatever the store keys on, and for Dataverse that is a
   * systemuser GUID — which renders as "Someone" everywhere a name is expected.
   * Optional, exactly like `ActivityEntry.actorName`: hosts whose key is already an
   * identity (the .NET side stores a UserId) omit it and callers fall back.
   */
  startedByName?: string | null;
  /**
   * Whether the calling user recorded this adoption.
   *
   * Resolved by the provider, not derived by the caller — and that is the whole point.
   * `startedBy` is whatever the store keys on, which for Dataverse is a systemuser
   * GUID, while `CurrentUser.id` is an Azure DevOps UPN. Those two id spaces cannot be
   * joined client-side (see the standing decision in CHECKPOINT.md), so a UI comparing
   * them gets `false` for the real adopter every time. The provider holds both ids in
   * the same space and answers the question there.
   *
   * Same arrangement, and for the same reason, as `VoteSummary.votedByMe`: a control
   * whose availability depends on per-user state cannot be rendered without it.
   * `canManageAdoption` takes this flag directly.
   */
  startedByMe: boolean;
  projectName: string;
  team: string | null;
  status: AdoptionStatus;
  startedAt: string;
  updatedAt: string;
  completedAt: string | null;
}

// startedByName and startedByMe are resolved by the adapter and have no wire
// counterpart; every other field still has to exist on the generated DTO.
export type AdoptionMatchesWire = Assert<
  FieldsExistOnExcept<Adoption, SolutionUseResponse, "startedByName" | "startedByMe">
>;

export interface StartAdoptionInput {
  projectName: string;
  team?: string;
  status?: AdoptionStatus;
}

export interface UpdateAdoptionInput {
  status?: AdoptionStatus;
  projectName?: string;
  team?: string;
}

// ---------------------------------------------------------------------------
// Participation
// ---------------------------------------------------------------------------

/**
 * Someone asking to help with an idea or solution.
 *
 * NOTE: `ParticipationResponse` and `RequestParticipationRequest` exist in
 * Momentum.Contracts and are generated by TypeGen, but the generated barrel
 * (`packages/contracts/src/generated.ts`) does not re-export them, so there is no
 * wire type to guard against here yet. Add the assertion once the barrel is
 * regenerated.
 */
export interface Participation {
  id: string;
  itemType: HubItemType;
  itemId: string;
  requestedBy: string;
  message: string;
  status: ParticipationStatus;
  decidedBy: string | null;
  rationale: string | null;
  createdAt: string;
  updatedAt: string;
  decidedAt: string | null;
}

export interface RequestParticipationInput {
  itemType: HubItemType;
  itemId: string;
  message: string;
}

// ---------------------------------------------------------------------------
// Links
// ---------------------------------------------------------------------------

/**
 * A claim that a solution answers an idea, and the decision on it.
 *
 * **Three things need approval: ideas, solutions, and the links between them.** This
 * carried no approval state for a while, on the reasoning that linking was a reviewer
 * action so nothing could ever be pending. Linking is open now — seeing both items is
 * the gate — so the pending state is back, and with it the reason for a row.
 *
 * Where each half lives, which is the whole design:
 *
 * - **Dataverse holds the proposal.** Pending, Approved or Rejected, with who proposed
 *   it, who decided and why.
 * - **Azure DevOps holds approved truth only.** The `Related` link is created at the
 *   moment of approval and never before.
 *
 * So a pending link is invisible in ADO, deliberately. That is what lets every reader
 * of ADO relations — the work item link panel, WIQL, `listLinkedSolutions` — be right
 * with no approval filter to remember. The cost is that the app must show a proposal
 * itself, or proposing one looks like it did nothing.
 *
 * The relationship taxonomy (Proposed / Relevant / Existing) is NOT coming back. It
 * described what kind of answer a solution was and nobody ever acted on it; approval
 * asks whether the claim is true at all, which is the question that was actually being
 * avoided.
 */
export interface IdeaSolutionLink {
  ideaId: string;
  solutionId: string;
  /** Who proposed it. Named `addedBy` since before there was anything to decide. */
  addedBy: string;
  addedAt: string;
  approval: ApprovalState;
  decidedBy: string | null;
  rationale: string | null;
  decidedAt: string | null;
}

/**
 * A proposed link waiting on a reviewer, carrying both titles.
 *
 * The titles are the reason this is its own type rather than an `IdeaSolutionLink`.
 * The review queue renders "<solution> answers <idea>" and a reviewer cannot decide on
 * two work item ids — so the provider resolves both while it has the rows in hand,
 * rather than making the queue fetch each one.
 */
export interface PendingLink {
  ideaId: string;
  ideaTitle: string;
  solutionId: string;
  solutionTitle: string;
  addedBy: string;
  addedAt: string;
}
