/**
 * @momentum/contracts
 *
 * Re-exports the TypeScript interfaces generated by TypeGen from the C# project
 * `src/Momentum.Contracts/Models.cs`.
 *
 * Run `pnpm generate` in this package to regenerate the files.
 */

export type {
  AcceptanceDecisionRequest,
  ActivityResponseItem,
  AddCommentRequest,
  AddVoteRequest,
  AppUser,
  AttachmentResponse,
  CommentResponse,
  CreateRequestRequest,
  CreateSolutionRequest,
  LinkSolutionRequestBody,
  RemoveVoteRequest,
  RequestResponse,
  RequestSummaryEntry,
  SearchResponse,
  SearchResponseItem,
  SelectCanonicalSolutionRequestBody,
  SetVisibilityRequest,
  SolutionResponse,
  SolutionSummaryEntry,
  SolutionUseResponse,
  StartSolutionUseRequest,
  UpdateRequestRequest,
  UpdateSolutionUseRequest,
  UploadAttachmentRequest,
  VoteSummaryResponse,
} from "./generated.js";
