/**
 * @momentum/contracts
 *
 * Re-exports the TypeScript interfaces generated by TypeGen from the C# project
 * `src/Momentum.Contracts/Models.cs`.
 *
 * Run `pnpm generate` in this package to regenerate the files.
 */
export type { AcceptanceDecisionRequest, AddCommentRequest, AddVoteRequest, AppUser, CommentResponse, CreateRequestRequest, CreateSolutionRequest, LinkSolutionRequestBody, RemoveVoteRequest, RequestResponse, SearchResponse, SearchResponseItem, SelectCanonicalSolutionRequestBody, SolutionResponse, SolutionUseResponse, StartSolutionUseRequest, UpdateRequestRequest, UpdateSolutionUseRequest, } from "./generated.js";
//# sourceMappingURL=index.d.ts.map