/**
 * @momentum/contracts
 *
 * Re-exports the TypeScript interfaces generated by TypeGen from the C# project
 * `src/Momentum.Contracts/Models.cs`.
 *
 * Run `pnpm generate` in this package to regenerate the files.
 */
export {};
//# sourceMappingURL=index.js.map