<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>44c27cb6-d69b-4f88-8430-5934aa0d52a8</UserSecretsId>
    <NoWarn>$(NoWarn);MCPEXP001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Momentum.ServiceDefaults\Momentum.ServiceDefaults.csproj" />
  </ItemGroup>

  <Target Name="CopyWwwrootToOutput" AfterTargets="Build">
    <ItemGroup>
      <WwwrootFiles Include="$(MSBuildProjectDirectory)\wwwroot\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(WwwrootFiles)" DestinationFolder="$(OutDir)wwwroot\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
