<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Momentum.Library\Momentum.Library.Application\Momentum.Library.Application.csproj" />
    <ProjectReference Include="..\Momentum.Library\Momentum.Library.Runtime\Momentum.Library.Runtime.csproj" />
    <ProjectReference Include="..\Momentum.Library\Momentum.Library.Infrastructure\Momentum.Library.Infrastructure.csproj" />
  </ItemGroup>
</Project>