<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.Abstractions" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Momentum.Library.Application\Momentum.Library.Application.csproj" />
  </ItemGroup>
</Project>
